# Generated by Django 5.0.5 on 2024-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0002_userprofile_age_userprofile_gender_userprofile_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('gain_weight', 'Gain weight'), ('lose_weight', 'Lose weight'), ('get_fitter', 'Get fitter'), ('gain_flexibility', 'Gain more flexible'), ('learn_the_basic', 'Learn the basic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_activity_level',
            field=models.CharField(choices=[('rookie', 'Rookie'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advance'), ('true_beast', 'True beast')], max_length=20),
        ),
    ]
