# Generated by Django 5.0.5 on 2024-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_alter_userprofile_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
