# Generated by Django 5.0.6 on 2024-06-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationCode',
        ),
    ]
