# Generated by Django 5.0.6 on 2024-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0007_delete_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_photos/'),
        ),
    ]
