# Generated by Django 5.0.5 on 2024-05-20 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercises/videos/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('exercises', models.ManyToManyField(related_name='workouts', to='courses.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Total duration in days')),
                ('category', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('is_pro', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='courses', to='courses.tag')),
                ('workouts', models.ManyToManyField(blank=True, related_name='courses', to='courses.workout')),
            ],
        ),
    ]
