# Generated by Django 5.0.5 on 2024-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Total duration in days')),
                ('category', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('is_pro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercises/videos/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('exercises', models.ManyToManyField(related_name='workouts', to='courses.exercises')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='courses',
            name='workouts',
            field=models.ManyToManyField(related_name='courses', to='courses.workouts'),
        ),
    ]
