# Generated by Django 5.0.5 on 2024-05-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tag_courses_hidden_courses_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
