# Generated by Django 5.0.5 on 2024-05-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.workout'),
        ),
    ]
